index:
    path: /
    controller: App\Controller\AppController::indexAction

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

admin:
    path: /admin
    controller: App\Controller\AdminController::index

admin_users_list:
    path: /admin/users
    controller: App\Controller\Admin\UserController::userList
